apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-30T16:15:58Z"
  name: currency-conversion
  namespace: default
  resourceVersion: "1860708"
  uid: 629c6ef7-3005-4c27-b6f9-fb885f39d8fb
